### ISSUE TITLE
The HTML version renders code blocks in white - invisible with white background.

### ISSUE THREAD

**Issue by rolfschr** [rolfschr/GSWL-book#12]
The pandoc.css contains styles to renders ``embedded code text`` white (line 125???). This is invisible on white backgrounds, ex:

![gswl_book_html](https://user-images.githubusercontent.com/1188465/53286759-842fc280-3773-11e9-89c5-1f7348721751.png)

Need to update the CSS.

**Comment by rolfschr** [comment]
@NickSeagull I guess you might be able to fix this better than me.

**Comment by avinash311** [comment]
This is still a problem.
January 27, 2019 e7a1468
screenshot attached
![white-text](https://user-images.githubusercontent.com/8648881/60727290-8cf78880-9f0b-11e9-9c78-d1d2f968f5e2.png)

**Comment by rolfschr** [comment]
@avinash311 This is fixed in 1868f6b. The issue was not related to the CSS style.
