### ISSUE TITLE
How to format ledger balance with 2 digits after decimal point?

### ISSUE THREAD

**Issue by zzgab** [rolfschr/GSWL-book#15]
Hi Rolf, I tried to find in your book (and in man and official doc, of course) how to display the balances with 2 decimal digits, even for integer amounts, but couldn't find an example.
Do you have an advice to share? Thanks!

**Comment by rolfschr** [comment]
Hi zzgab, you can define a commodity's format. Checkout the `commodity` section in chapter [4.7.2](https://www.ledger-cli.org/3.0/doc/ledger3.html#Journal-Format)

```
$ cat tmp/test.txt 
commodity EUR
   format EUR1,000.000

2013/05/01 * Init
 Expenses:Unknown
 Expenses:Bike  23 EUR


$ ledger -f tmp/test.txt bal                                                                                                                                                                                   
                   0  Expenses
          23.000 EUR    Bike
         -23.000 EUR    Unknown
--------------------
                   0
```

BUT: You don't have to do this. Ledger observes the input format and will imitate it. Simply use two digits in your journal file:

```
$ cat tmp/test.txt                                                                                                                                                                                             
2013/05/01 * Init
 Expenses:Unknown
 Expenses:Bike  23.00 EUR ; mind the additional ".00"

$ ledger -f tmp/test.txt bal                                                                                                                                                                                   
                   0  Expenses
           23.00 EUR    Bike
          -23.00 EUR    Unknown
--------------------
                   0
```

**Comment by zzgab** [comment]
Thank you for your response.
So I understand that it is mandatory to specify the currency every time.
I was expecting to find a way to configure the default format for amounts, and to omit the currency symbol.

**Comment by rolfschr** [comment]
I see, I don't know this right now. Why do you want to omit the currency symbol? Would a postprocess shell script that adds the symbol automatically do the job?

**Comment by zzgab** [comment]
Given that I only use one currency in this particular ledger book, I thought it simply adds verbosity to the transaction declarations -- and to the reports. So, I wanted to omit the currency symbol altogether.
I guess a pre-processing job could do, as well as a post-processing to remove it again from the output, as the rest of my automated chain (the producing of PDF invoices etc.) expects amounts without currency symbol.
Thanks anyway!
