### ISSUE TITLE
German translation?

### ISSUE THREAD

**Issue by kthth** [rolfschr/GSWL-book#18]
I'd be interested in participating in/doing a German version of this great guide. Can I just go ahead in my fork?

**Comment by rolfschr** [comment]
Mh, a couple of comments
- Sure, it's open source.
- I think any German willing to learn Ledger will be able to speak English good enough. I don't think it's worth the effort for the Germane language.
- [This guy](https://github.com/deild/GSWL-book) started a french translation (which I found out by accident). I believe he added some improvements independently from the translation efforts (Makefile, ...). Maybe you can join forces.
- I personally would love to have a repo that contains multiple languages (say 01_en.md, 01_de.md, ...) but I lack the time to prepare the code for this.
