### ISSUE TITLE
Confusion about accounts

### ISSUE THREAD

**Issue by tbm** [rolfschr/GSWL-book#21]
The book says:

> Example accounts may be “Groceries”, “Bike”, “Holidays”, “Checking Account of Bank X”, “Salary” or “Mortgage”.

Technically, the account would be Expneses:Groceries, etc.  Maybe you should say something like:

Categories could include things like "Groceries".... In ledger, these would be expressed as accounts by prepending `Expenses`, e.g. `Expenses:Groceries`.

**Comment by tbm** [comment]
Same issue later, e.g.

> For example, buying a book online for $15 moves money from the account “Creditcard X” to the account “Books”.

**Comment by rolfschr** [comment]
Well, this section is first and foremost meant as an introduction to double accounting. I don't want to complicate things. Besides, the ``alias`` sub-directive would allow me to use the unqualified account names.
