### ISSUE TITLE
Is WSL an easier way in 2023 to run ledger?

### ISSUE THREAD

**Issue by jayrajput** [rolfschr/GSWL-book#27]
> https://github.com/rolfschr/GSWL-book/blob/dd833b7531730a2d29553d0dd05e8dbe009b64bd/02-ledger-accounting/01-double-accounting.md?plain=1#L163

This refers to VirtualBox and I wonder if WSL2 might be an easier way to run ledger. Let me know if you want me to send a pull request on usage of WSL2.

**Comment by rolfschr** [comment]
Hi @jayrajput,

yes, sure, go ahead with a PR. Don't forget to add yourself to the contributors if you want to!

**Comment by jayrajput** [comment]
Submitted https://github.com/rolfschr/GSWL-book/pull/28. How does one go about verifying the final html to make sure I have not broken something.
