### ISSUE TITLE
Add EPUB to releases

### ISSUE THREAD

**Issue by lkraav** [rolfschr/GSWL-book#3]
Hi. Due to the humongous numbers of dependencies that a `pandoc` installation requires, do you think you could also publish an EPUB release next to the PDF?

EPUB can be formatted significantly better on some mobile e-readers.

**Comment by rolfschr** [comment]
Hi,

yes, I can do that but I don't plan to release a new version soon (nothing to be done currently). The Makefile already contains a `epub` target (using pandoc) which I used to generated the attached file. I named it ".zip" to trick Github (allowed file extension) but it is really an *.epub file:
[GettingStartedWithLedger.epub.zip](https://github.com/rolfschr/GSWL-book/files/288434/GettingStartedWithLedger.epub.zip)

That thould help you I guess.

Best,
Rolf

**Comment by lkraav** [comment]
Thanks, this helped very well.
