### ISSUE TITLE
needs a web version

### ISSUE THREAD

**Issue by simonmichael** [rolfschr/GSWL-book#5]
I recommended this book today, but IMHO it takes too many clicks to get it on screen, not all of them obvious. (In latest firefox on mac, 5 clicks from the plaintextaccounting page.) I think this book is excellent and should be much better known. I think it needs a web version you can click directly to and see the table of contents right away.

**Comment by alexjj** [comment]
[Gitbook](https://www.gitbook.com) is a nice tool for making web books plus it generates epub etc. The layout of the repo would need to be changed slightly but it takes markdown.

I just count two clicks from your page to the pdf. Possibly you changed it, but it links to the latest releases page and then click on the pdf.

**Comment by simonmichael** [comment]
Here's how it looks for me:

0. starting at http://plaintextaccounting.org/#docs
1. click Getting Started With Ledger
2. click GettingStartedWithLedger.pdf (non-obvious smaller link)
3. firefox dialog "You have chosen to open... would you like to save this file ?" appears. Wait for save file button to enable. Click save file.
4. click the completed download icon in browser toolbar at top right.
5. click the top item, GettingStartedWithLedger.pdf.
6. (bonus step!) PDF opens in Preview. Flail around at command keys until you find the one that opens the table of contents pane. (Nice that there is a table of contents by the way.)

**Comment by rolfschr** [comment]
Hi @simonmichael thanks for your comments. I have added a HTML version to the latest release. The PDF was already the closest you can get without self-hosting it, I guess. I understand your wish but I would expect people looking for "plain text accounting" are fine with the downloadable PDF/HTML. An online version might be good for SEO. By the way, I didn't know the book was referenced!

**Comment by simonmichael** [comment]
@rolfschr good progress. It's still five clicks in my firefox, because the html like the pdf is treated as a downloadable file you must save and open. This means (I think) that it is not indexed by search engines, we can not link to locations within it, and therefore it will continue to be largely unknown.

**Comment by rolfschr** [comment]
Hi @simonmichael exactly. By "online version" I did not mean the release HTML I added but a proper page - which doesn't exist currently. I still believe people looking for command line accounting will manage. It's a niche anyway. I currently don't have plans to host a web version of the book anywhere so I'm unsure how to deal with this github issue. I'm gonna leave it open for now.

**Comment by simonmichael** [comment]
I see @rolfschr. Well, if you or someone would like to add the HTML version as a page on plaintextaccounting.org, that could work well I think. I think the niche can become a bigger niche but only if the learning materials are accessible.

**Comment by jgonsior** [comment]
Maybe instead of hosting it on your own you could just let [GitHub](https://pages.github.com/) host the page for  you (and us)?

**Comment by rolfschr** [comment]
@jgonsior yeah, good idea. Also made me try out this github feature! Here it is:

https://github.com/rolfschr/GSWL-book#get-the-book
https://rolfschr.github.io/gswl-book/latest.html

**Comment by simonmichael** [comment]
Much better! I updated the link at http://plaintextaccounting.org/#docs .
