### ISSUE TITLE
Syntax error in reports.py

### ISSUE THREAD

**Issue by RidaAyed** [rolfschr/GSWL-book#7]
Hi

Running
`$ ledreports`

returns
`
  File "/home/ra/src/GSWL-ecosystem/reports.py", line 68
    def show((expl, cmds)):
             ^
SyntaxError: invalid syntax
`

Any ideas?

https://github.com/rolfschr/GSWL-ecosystem/blob/master/reports.py#L68

**Comment by rolfschr** [comment]
Hi,
which Python version are you using (``python -V``)?

**Comment by RidaAyed** [comment]
Hi

Thank you.

3.6.4

**Comment by rolfschr** [comment]
Ah, ok a quick google shows a syntax change in py3 (https://www.python.org/dev/peps/pep-3113/). I think

def show(**report**):
    """
    Show one report from the report file.
    """
    **expl, cmds = report**
   ...


Should do the trick. I don't have the time to test right now.

**Comment by RidaAyed** [comment]
Does the trick :+1:

**Comment by rolfschr** [comment]
For reference: https://github.com/rolfschr/GSWL-ecosystem/commit/01e71390fa2aa1e8407843d1ddf65f288a8d90a2
