### ISSUE TITLE
Convert.py name file is not defined

### ISSUE THREAD

**Issue by RidaAyed** [rolfschr/GSWL-book#9]
Hi

Executing `lmnorthbank` in tmux panel *make* returns:
![Screenshot](https://i.imgur.com/PxbaYqP.png)

Mind my folder changes here. Originally it pointed to current 'eco' folder instead of 'private' folder:
https://gist.github.com/RidaAyed/411e8fdcdde49f3ed022d605b687c638#file-convert-py-L14

:angry: for putting a screenshot instead of plaintext (don't know tmux well enough yet)

Concerns book chapter: https://rolfschr.github.io/gswl-book/latest.html#Get_data_from_Northbank

**Comment by YoniFei** [comment]
Try changing `f = file(CONFIG_FILE, 'r')` to `f = open(CONFIG_FILE, 'r')` in convert.py

**Comment by RidaAyed** [comment]
Changing line 84 in `convert.py` to
`f = open(CONFIG_FILE, 'r')`
results in https://github.com/rolfschr/GSWL-ecosystem/issues/4

**Comment by RidaAyed** [comment]
This issue is obsolete if python 2.7 is used https://github.com/rolfschr/GSWL-ecosystem/issues/4#issuecomment-368225540

**Comment by rolfschr** [comment]
See https://github.com/rolfschr/GSWL-ecosystem/issues/4#issuecomment-369220927
